language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.8
  - rvm: 2.4.6
  - rvm: 2.5.5
  - rvm: 2.6.3
  - rvm: ruby-head
  - rvm: jruby-head
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
sudo: false
cache: bundler
before_install: gem install bundler
script: bundle exec rspec
